# Generated by Django 6.0.5 on 2026-05-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('prazo', models.DateField()),
                ('status', models.CharField(choices=[('a_fazer', 'A Fazer'), ('desenvolvimento', 'Desenvolvimento'), ('completo', 'Completo'), ('Analisar', 'Analise')], default='a_fazer', max_length=20)),
            ],
        ),
    ]
